#!/usr/bin/env bash

brew_deps() {
    deps=(stow)
    brew install "${deps[@]}"
}

create_link() { srcdir="${1}" destdir="${2}"
    stow --verbose --dotfiles "${srcdir}" --target="${destdir}"
}

create_batch() { destdir="${1}"; shift; packages=( "${@}" )
    mkdir -p "${destdir}"
    for package in "${packages[@]}"; do
        create_link "${package}" "${destdir}"
    done
}

main() {
    create_batch "${HOME}" \
        bash git vim tmux
    create_batch "${HOME}/.config/Code/User" \
        vscode
    create_batch "${HOME}/.var/app/io.mpv.Mpv/config/mpv" \
        mpv
}
main "${@}"
