#!/bin/bash
#-------------------------------------------------------------------------------
# x220t_install - just managing my configs :^)
#-------------------------------------------------------------------------------

dir="${HOME}/git/dotfiles/src_x220t"
files=(
    .gitconfig
    .gitignore_global
    .vimrc
    .bashrc
    .bash_aliases
    .bash_profile
    .dircolors
    .inputrc
    .tmux.conf
    .tmux-gitbar.conf
    .XCompose
    .xprofile
    .ncmpcpp/bindings
    .ncmpcpp/config
    .config/compton.conf
    .config/xfce4/terminal/terminalrc
    .config/mpdnotify.conf
    .config/mpd/mpd.conf
    .config/mpv/mpv.conf
    bin/listppa
    bin/startvm
    bin/unarchive
    bin/padding-check
    bin/tag-check
    bin/music-sync
)

#-------------------------------------------------------------------------------

# Change directory to dotfiles directory
cd "${dir}"

# Start symlinking
printf "Symlinking\n"
for file in "${files[@]}"; do
    printf "    %s\n" "${file}"
    ln -sfn "${dir}/${file}" "${HOME}/${file}"
done
